# Generated by Django 5.1.1 on 2024-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
