# Generated by Django 5.1.1 on 2024-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrders', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('τεμ', 'Τεμάχιο'), ('παλέτα', 'Παλέτα'), ('κιβώτιο', 'Κιβώτιο')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
