# Generated by Django 5.1.1 on 2024-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrders', '0005_product_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Άρτος', 'Άρτος'), ('Γλυκά', 'Γλυκά'), ('Καβά', 'Καβά'), ('Καφές & Ροφήματα', 'Καφές & Ροφήματα'), ('Κουλούρια/Μπισκότα', 'Κουλούρια/Μπισκότα'), ('Κριτσίνια', 'Κριτσίνια'), ('Σάντουιτς', 'Σάντουιτς'), ('Τυροπιτιέρα', 'Τυροπιτιέρα'), ('Αναλώσιμα', 'Αναλώσιμα')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(choices=[('kg', 'kg'), ('τεμ', 'τεμ'), ('Παλέτα', 'Παλέτα'), ('Κιβώτιο', 'Κιβώτιο')], max_length=50),
        ),
    ]
