# Generated by Django 5.1.1 on 2024-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrders', '0006_alter_product_category_alter_product_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
