# Generated by Django 5.1.1 on 2024-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrders', '0007_orderitem_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
