# Generated by Django 5.1.1 on 2024-09-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_suppliers_employee_salary_employee_totalsalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
