# Generated by Django 5.1.1 on 2024-10-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_surname_employee_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='currentMoney',
        ),
        migrations.AddField(
            model_name='employee',
            name='IBAN',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
