# Generated by Django 5.1.1 on 2024-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_suppliers_currentmoney_employee_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='PID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
