# Generated by Django 5.1.1 on 2024-11-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_suppliers_last_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='last_balance',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='ownMoney',
        ),
    ]
