# Generated by Django 5.1.1 on 2024-10-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0005_remove_suppliers_currentmoney_employee_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.suppliers')),
            ],
        ),
    ]
